#bash cli_reptile_ddp_prompt_noqa2qa.sh
bash cli_reptile_ddp_prompt_qa2qa.sh
bash cli_reptile_ddp_prompt_nonli2nli.sh
bash singletask_from_reptile_noqa2qa.sh
bash singletask_from_reptile_qa2qa.sh
bash singletask_from_reptile_nonli2nli.sh
